name: Deploy Staging 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    timeout-minutes: 30


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy files to staging server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USER_NAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          source: "."
          target: "/home/ubuntu/staging/Mentoring-DevOps---Pacmusic"

      - name: Run docker compose in staging
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST_STAGING }}
          username: ${{ secrets.SSH_USER_NAME_STAGING }}
          key: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          script: |
            cd /home/ubuntu/staging/Mentoring-DevOps---Pacmusic
            docker compose up -d --build pacmusic-stg

      - name: Test endpoint staging
        run: curl -f ${{ secrets.STG_URL }}
