name: Deploy Production

on:
  release:
    types: [published, edited]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy files to production server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USER_NAME_PRODUCTION }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}
          source: "."
          target: "/home/ubuntu/production/Mentoring-DevOps---Pacmusic"

      - name: Run docker compose in production
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USER_NAME_PRODUCTION }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}
          script: |
            cd /home/ubuntu/production/Mentoring-DevOps---Pacmusic
            docker compose up -d --build pacmusic-prod

      - name: Test endpoint production
        run: curl -f ${{ secrets.PROD_URL }}
